### ISSUE TITLE
why are number values (e.g. app or vm 'id') returned by RavelloClient functions sometimes int and other times unicode?

### ISSUE THREAD

**Issue by ryran** [ravello/python-sdk#21] opened 2015-01-29 20:09 UTC
```
>>> r = ravello_sdk.RavelloClient() ; r.login(user, passwd)
>>> x = r.get_applications()[0]['id']; type(x) ; x
<type 'unicode'>
u'53936161'

>>> r = ravello_sdk.RavelloClient() ; r.login(user, passwd)
>>> x = r.get_applications()[0]['id']; type(x) ; x
<type 'int'>
53936161

>>> u = 0 ; i = 0

>>> for _ in range(200):
...     r = ravello_sdk.RavelloClient() ; r.login(user, passwd)
...     id = r.get_applications()[0]['id']
...     if isinstance(id, int):
...             i += 1
...     else:
...             u += 1
... 

>>> i
99

>>> u
101
```

**Comment by ryran** [comment] 2015-01-29 20:45
This seems to me like it has to be in the SDK (as opposed to the API), but just to rule it out I tried something similar with `curl`. Have little to no experience with XML but it seems to be a fair test.

```
[rsaw]$ APPID=53936161
[rsaw]$ for _ in {1..200}; do curl -s --user "${USERNAME}:${PASSWD}" -X GET -H "Content-Type: application/xml" "https://cloud.ravellosystems.com/api/v1/applications/${APPID};properties" | grep -o 'encoding.* id=.*"'; done | sort | uniq -c
    200 encoding="UTF-8" standalone="yes"?><ns2:application xmlns:ns2="http://ravellosystems.com/management" id="53936161"
```
That is to say: I got the same result 200 times.

**Comment by hadard** [comment] 2015-02-02 19:30
Hi @ryran, we were able to reproduce the problem and it seems like a problem in our backend system and not in the python sdk. Is this issue holding you in anyway?

**Comment by ryran** [comment] 2015-02-02 22:08
Well @hadard I'm not sure when it started ... or if it's always been like that and I only just now have code that helps me notice it (see above-linked issue). Really I'm most interested in consistency. I just want to know what I should code for.

Since this new issue has cropped up I haven't done any thorough testing looking for bugs (I haven't built unit tests for our application yet).

**Comment by hadard** [comment] 2015-02-03 08:12
@ryran our preliminary analyse indicate that the problem is probably there for long time. My suggestion is to add ugly patch that try to cast to int in any case (int(app['id'])). 
If it's a problem for you, we can prioritize the deep analyze and the fix higher.

**Comment by ryran** [comment] 2015-02-03 22:18
> *... it seems like a problem in our backend system and not in the python sdk*

Really? Wow. That surprises me.

> *My suggestion is to add ugly patch that try to cast to int in any case (int(app['id'])).*

@hadard: Yeah that's what I'm doing already in one spot. I guess I'll go through my code and make sure I do that everywhere.

**Comment by gilhoffer** [comment] 2015-02-04 07:05
@ryran ,yes, we have pinpointed the issue, and will release a fix there quite soon.
The reason you didn't see it with your test using cURL, is that the issue hits some fields (in some cases) only when using JSON and not XML as the Content-Type.
We will let you know once the fix will be applied to our backend, and you can eliminate this cast.

**Comment by gilhoffer** [comment] 2015-02-04 07:09
Just noticed this fix was applied about an hour ago (6:13am GMT).
Please let us know if you still encounter this issue (preferably by a support ticket, or an email to support AT ravellosystems.com) - in any case I'm going ahead and closing this one.

**Closed by gilhoffer** 2015-02-04 07:09 UTC

**Comment by ryran** [comment] 2015-02-04 19:42
> *The reason you didn't see it with your test using cURL, is that the issue hits some fields (in some cases) only when using JSON and not XML as the Content-Type.*

@gilhoffer, I appreciate the explanation.

> *Just noticed this fix was applied about an hour ago (6:13am GMT). Please let us know if you still encounter this issue...*

Thank you!
